- name: Install swarm
  sudo: yes
  copy: >
    src=swarm-{{ swarm_version }}
    dest=/usr/local/bin/swarm
    owner=root
    group=root
    mode=0777

- include: ./swarm_join.yml
  tags:
    - swarm_join


