- name: Install swarm client upstart 
  template: >
    src=swarm_client.upstart.j2
    dest=/etc/init/swarm_client.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart swarm client
  sudo: yes

- name: Start and enable Swarm client
  sudo: yes
  service: >
    name=swarm_client
    state=started
    enabled=true
