- name: Add docker apt repository key
  sudo: yes
  apt_key: url=https://get.docker.io/gpg state=present validate_certs=no

- name: Add docker apt repository
  sudo: yes
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install latest docker via apt
  sudo: yes
  apt: pkg=lxc-docker state=latest 

- name: Add user to Docker group
  sudo: yes
  user: name={{ ansible_user_id }} groups=docker append=yes

- name: Install /etc/default/docker
  sudo: yes
  template: > 
      src=docker.default.j2
      dest=/etc/default/docker
      owner=root
      group=root
      mode=0644
  notify: restart docker

- name: Start docker on boot
  sudo: yes
  service: name=docker state=started enabled=yes

