---

- hosts: dockerhosts
  sudo: no
  roles:
      - docker
      - { role: "swarm", tags: ["join"] }
  tasks:
    - name: Pull images
      sudo: True
      command: >
        docker pull {{ item }}:latest
      with_items: docker_images





