---

- hosts: dockerhosts
  sudo: no
  roles:
      - docker
      #      - docker_swarm
  tasks:
    - name: Pull images
      sudo: True
      command: >
        docker pull {{ item }}:latest
      with_items: docker_images





